# Generated by Django 5.2.6 on 2025-09-20 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pressure_gauge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'gauge_type',
            },
        ),
        migrations.CreateModel(
            name='PressureGauge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(max_length=15)),
                ('resolution', models.CharField(max_length=20)),
                ('rbc_certificate_number', models.CharField(max_length=50)),
                ('calibration_date', models.DateField()),
                ('organization', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pressure_gauge.gaugetype')),
            ],
            options={
                'db_table': 'pressure_gauge',
            },
        ),
    ]
