# Generated by Django 5.2.6 on 2025-09-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_gauge', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressuregauge',
            old_name='type',
            new_name='gauge_type',
        ),
    ]
