# Generated by Django 5.2.6 on 2025-09-18 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fantasy_name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('cnpj_formated', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
