# Generated by Django 5.2.6 on 2025-09-20 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fantasy_name', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('cnpj_formated', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
