# Generated by Django 5.2.6 on 2025-09-20 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('validate_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worder_order',
            },
        ),
    ]
