# Generated by Django 5.2.6 on 2025-09-18 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyValve',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='Safety Valve', max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(max_length=20)),
                ('actuation_range', models.CharField(max_length=50)),
            ],
        ),
    ]
